### ISSUE TITLE
Preparing Vazir for Google Fonts

### ISSUE THREAD

**Issue by yanone** [rastikerdar/vazirmatn#231]
Hello,

I've been commissioned to onboard Vazir to Google Fonts.
We’re interested only in the Variable Font TTF. The rest will be generated from that by Google engineers on their servers.

I’m wondering how to proceed practically: Whether to fork the repo and apply the changes required by our specifications or whether to PR the changes back to you.

As far as I can tell at the moment, the changes would be:

* Copyright field in name table change to `Copyright 2015 The Vazir Project Authors (https://github.com/rastikerdar/vazir-font)`
* Eliminate nested components
* Instance weight values `300`, `500`, and `700` instead of `250.0`, `566.6665954589844`, and `733.3332977294922` (See https://github.com/googlefonts/gf-docs/tree/main/Spec#axes)
* Bit 3 of the `head` table needs to be set for PPEM rounding, since this is a hinted font
* Add `STAT` and `avar` tables
* `OS/2.fsSelection` bit 7 needs to be set (Use Typo metrics)
* Adjustments to vertical metrics (`OS/2.usWinDescent` to `1116` instead of `1100`)
* Decompose transformed components

Since Vazir seems to be a very popular font available for a multitude of environments, please let me know whether you are comfortable with the proposed changes to your repo or not.

Thank you.

**Comment by yanone** [comment]
I’m asked to also onboard Shabnam and Sahel. So the above question applies to all three. The issues with the two other fonts are also somewhat similar.

**Comment by rastikerdar** [comment]
Thank you Yanone!
I'm trying to fix the issues reported by fontbakery. Since I use Fontforge, it's kind of hard to find solutions, but I'm trying. Thanks again.

**Comment by i14h** [comment]
@rastikerdar thanks for helping! Let us know if you need a hand.

**Comment by bateni** [comment]
@yanone do you have ideas for how to fix the fontbakery problems for this particular font? For example, would you send PRs to fix PPEM rounding, `STAT`, `avar` as "post-processing"? Or are there settings inside Fontforge that will address this automatically? Same question about nested components? It's easier to design with nested components, could one fix them in post-processing?

**Comment by yanone** [comment]
I’m not versed in Fontforge-based font production, as it’s rather seldomly used. So I sadly can’t answer any of the questions off the top of my head. Even for me, every situation is different and I need to sit and investigate myself.

Before I can answer them, my question remains to whether you would like to engineer the problems yourself or leave it to me and PR the changes back to you. Or, third option, whether we should fork the repository.

It’s part of my work to engineer those things even if they seem complicated. Both approaches, fixing the sources as well as hot-fixing the binaries, are thinkable. If I prepared a PR, all changes would be documented transparently in the PR and you would still be in control of what’s happening, as you can reject a PR or ask me to change certain aspects if you don’t approve of them.

But if I sit now and research the individual issues, then I will have essentially already done the work, in which case I’d prefer to just prepare a complete PR. I’m getting paid to do that, so it’s totally fine with me.

Sorry for the complicated reply :)

**Comment by rastikerdar** [comment]
No problem. I think I fixed all the issues but there are many changes to upload. I will upload them to a new branch.

**Comment by yanone** [comment]
So, I looked at the font a bit. Since you're generating UFOs, you can use fontmake’s `FlattenComponents` filter for the nested components.
Sorry if this comes too late. What other issues do you struggle with?

**Comment by rastikerdar** [comment]
I'm going to change the name of this font from "Vazir" to "Vazirmatn". There are some reasons for this. However, the new version is 32.0.0 that continues the latest Vazir version.
I have made a big update to this font in design, build scripts, folder structures, ... I pushed all these changes into a new branch called Vazirmatn and explained about the scripts and commands in `README.md` located in folder `scripts`. 

https://github.com/rastikerdar/vazir-font/tree/vazirmatn
https://github.com/rastikerdar/vazir-font/tree/vazirmatn/scripts

Please have look at that branch and tell me if i should fix or change anything. I will merge that branch into the `master` after renaming the repository. This is a pre-release version to check if build process is correct. I reduced the "fail" issues reported by `fontbakery check-googlefonts -F Vazirmatn\[wght\].ttf` to 1 issue but if you think this is not an important issuse for a Farsi/Arabic typeface I skip it: 
>      FAIL The following glyphs could not be attached to the
>          dotted circle glyph: - dotbelow - tildecomb - hook - uni030F -
>          gravecomb - And acutecomb [code: unattached-dotted-circle-marks]
Please review the variable or instances ttf to see if they pass. The variable is in `fonts/variable`.
It seems the family name of variable version should be "Vazirmatn", not "Vazirmatn Variable" or anything else. Am I right? I wonder how can we have both the static and variable installed at the same time when they have similar name!

## About weights
Vazir weights are synced with Roboto weights. Weights in Roboto family are not linear. As you can see in the variable repository of Roboto, Vazir is like Roboto. https://github.com/googlefonts/Roboto-Classic/blob/master/sources/Roboto.designspace
In the new version of Vazir (Vazirmatn) the build script tool clones the Roboto variable repo and merge the UFOs into Vazirmatn to generate the final ttfs. I cannot fix this issue because I have to redesign the heavy weight (to make it more fat) and that will make both fonts out of sync. However, I can turn it into something like this but the problem is the same:
```
    <axis maximum="900" minimum="100" tag="wght" default="400" name="weight">
      <labelname xml:lang="en">Weight</labelname>
      <map input="100" output="100" />
      <map input="200" output="230" />
      <map input="300" output="315" />
      <map input="400" output="400" />
      <map input="500" output="608" />
      <map input="600" output="679" />
      <map input="700" output="752" />
      <map input="800" output="825" />
      <map input="900" output="900" />
    </axis>
```

**Comment by davelab6** [comment]
Why not instantiate a "900" weight roman with the weight that matches
yours, from the weight axis of Roboto Classic? :)

**Comment by rastikerdar** [comment]
@davelab6 How? 🤔 Vazirmatn "900" already matches Roboto "900". 

![rect195](https://user-images.githubusercontent.com/3116038/156104077-739354a1-3e7d-48aa-a558-e0266403fe1b.png)

**Comment by bateni** [comment]
@davelab6 and @yanone: curious if you got a chance to look at Saber's new branch... is it ready for google-fonts?

**Comment by yanone** [comment]
@rastikerdar
Well done, it looks great. The dotted circle is a brand-new requirement and personally I say we can let it pass. I’ll also put a word in with our reviewers to do the same. I have never seen the dotted circle used in practice for Arabic scripts. We also have a `ufo2ft` filter in the works atm, which isn’t merged yet, which would create the glyph automatically on generating. Chances are, by the time everything is done, you can generate the fonts again to meet that requirement.

There are three more things I'd like to ask of you: 
1. Please prepare a DESCRIPTION.en_us.html file at the root of the repo similar to this one: https://github.com/erinmclaughlin/Hubballi/blob/master/DESCRIPTION.en_us.html and also keep the Github link at the bottom. The file must not be longer than 2000 characters incl. HTML code and whitespace. No need to include designer information in the description, as we’ll prepare this in a separate place. (see 3.)
2. Please design one or more images to be used for tweeting when the font goes live.
3. Since we don’t have a font of yours published yet (to my knowledge), please fill this form so that we can collect some information about you: https://docs.google.com/forms/d/e/1FAIpQLSeMwHN8J213ZaxHrr5lHCrX56HY_NjGrWB8o604g98YxuMrdA/viewform

Excellent work. Thank you.
please let us know when you have merged your new branch.

**Comment by i14h** [comment]
Woohoo! Great job Saber and thanks for all the effort you put into this! 🎉🎉🎉

**Comment by yanone** [comment]
Thank you. I’ve PR'd the fonts to google/fonts where they will be reviewed. After merging it takes around two weeks for the fonts to go live on average. That part is outside of our control and in the responsibility of another team of Google engineers.
https://github.com/google/fonts/pull/4352

**Comment by rastikerdar** [comment]
@yanone Thanks. I hope they use the weight values specified in the repository that the variable and instance files was produced based on :)
